### ISSUE TITLE
Create a full screen loading screen  using inspiration from the figma design

### ISSUE THREAD

**Issue by 1finedev** [Klin-Coders/hackathon-quiz#23]
here is the figma design you can see the colors to use 

https://www.figma.com/file/fe6o2KtQch9264aCK9yVrd/Hackerthon-4.0%F0%9F%A7%91%F0%9F%8F%BD%E2%80%8D%F0%9F%92%BB?node-id=0-1&t=n9sc00LYi7goHJOn-0

**Comment by Olulanke-Mainasara** [comment]
Would love to take this up 🚀
